models:
  - './save/2025-04-29_19-15-04/iter_29'
  - './save/2025-04-29_19-15-04/iter_final'
eval_dataset:
  path: "../data/announcer/labeling/preprocessed_test.pickle"
  audio_path: "../data/announcer/source"
  x: "soundpath"
  y: "script.text.ipa_array"
  loop: true
max_queue_size: 50000
refill_threshold: 10000
chunk_size: 40000
log:
  name: "ctc"
  stream: true
  file: true