log:
  name: "ctc"
  stream: true
  file: true

train_dataset:
  path: "../data/korean/preprocessed_train.pickle"
  audio_path: "."
  x: "soundpath"
  y: "script.text.ipa_array"

eval_dataset:
  path: "../data/korean/preprocessed_test.pickle"
  audio_path: "."
  x: "soundpath"
  y: "script.text.ipa_array"

data_loader:
  num_workers: 0
  drop_last: true

batch_size: 10
total_iter: 12000000
accumulation_steps: 64
print_steps: 8000
eval_steps: 100000
save_steps: 50000

max_queue_size: 50000
refill_threshold: 10000
chunk_size: 40000

optimizer_vale:
  lr: 1.0e-5
  weight_decay: 5.0e-3

trainer:
  freeze_feature_extractor: true

vocab_path: "./model/ipa_vocab_auto.json"
